#!/bin/sh

# TTY, where emptty will start.
export TTY_NUMBER=7

# Preselected user, if AUTOLOGIN is enabled, this user is logged in.
#export DEFAULT_USER=user

# Enables Autologin, if DEFAULT_USER is defined. Possible values are "true" or "false".
export AUTOLOGIN=false

# Default LANG, if user does not have set own in init script.
#export LANG=en_US.UTF-8