#!/bin/sh

# TTY, where emptty will start.
export TTY_NUMBER=7

# Preselected user, if AUTOLOGIN is enabled, this user is logged in.
#export DEFAULT_USER=user

# Enables Autologin, if DEFAULT_USER is defined. Possible values are "true" or "false".
export AUTOLOGIN=false

# Selects, which environment will be used. Possible values are "xorg" or "wayland".
# If "xorg" is selected, it expects to have prepared .xinitrc file with +x at home folder.
# If "wayland" is selected, it expects to have prepared .winitrc file with +x at home folder.
export ENVIRONMENT=xorg

# Fallback/default LANG, if user does not have set own in init script.
#export LANG=en_US.UTF-8