.TH EMPTTY 1 "July 2021" "emptty 0.5.2" emptty

.SH NAME
emptty \- Dead simple CLI Display Manager on TTY

.SH SYNOPSIS
.B emptty [-v] [--version] [-d] [--daemon] [-c PATH] [--config PATH] [-i] [--ignore-config] [-t TTY] [--tty TTY] [-u defaultUser] [--default-user defaultUser] [-a [session]] [--autologin [session]]

.SH DESCRIPTION
.B emptty
Simple CLI Display Manager, that allows to select DE/WM after login, use predefined config or allows autologin, if selected user is part of
.I nopasswdlogin
group.

.SH OPTIONS
.IP "\-v, \-\-version"
Display the version of the program.

.IP "\-d, \-\-daemon"
Starts emptty as daemon, that does not require agetty.

.IP "\-c, \-\-config PATH"
Loads configuration from specified path.

.IP "\-i, \-\-ignore-config"
Skips loading of configuration from file, loads only argument configuration.

.IP "\-t, \-\-tty TTY"
Overrides loaded configuration by setting defined TTY.

.IP "\-u, \-\-default-user defaultUser"
Overrides loaded configuration by setting defined defaultUser.

.IP "\-a, \-\-autologin [session]"
Overrides loaded configuration by enabling autologin. If session is defined, it overrides autologin session.

.SH CONFIG
/etc/emptty/conf

.IP TTY_NUMBER
TTY, where emptty will start.
.IP SWITCH_TTY
Enables switching to defined TTY number. Default is true.
.IP PRINT_ISSUE
Enables printing of /etc/issue in daemon mode.
.IP DEFAULT_USER
Preselected user, if AUTOLOGIN is enabled, this user is logged in.
.IP AUTOLOGIN
Enables Autologin, if DEFAULT_USER is defined. Possible values are "true" or "false". Default value is false.

.B NOTE:
to enable autologin DEFAULT_USER must be in group
.I nopasswdlogin
, otherwise user will NOT be authorized.
.IP AUTOLOGIN_SESSION
The default session used, if Autologin is enabled. If session is not found in list of session, it proceeds to manual selection.
.IP LANG
defines locale for all users. Default value is "en_US.UTF-8"
.IP DBUS_LAUNCH
Prepends "dbus-launch" before desktop command. Default value is true. If
.I .emptty
is handled as script, this config is overriden to false.
.IP XINITRC_LAUNCH
Starts Xorg desktop with calling
.I ~/.xinitrc
script, if is true, file exists and selected WM/DE is Xorg session, it overrides DBUS_LAUNCH. If
.I .emptty
is handled as script, this config is overriden to false.
.IP VERTICAL_SELECTION
Prints available WM/DE each on new line instead of printing on single line.
.IP LOGGING
Defines how logging is handled. Possible values are "default", "appending" or "disabled". Default value is "default".
.IP LOGGING_FILE
Overrides path of log file. Default value is
.I /var/log/emptty

.B NOTE:
It expects existence of directories to defined logging file.

.IP XORG_ARGS
Arguments passed to Xorg server.
.IP DYNAMIC_MOTD
Allows to use /etc/emptty/motd-gen.sh script to generate custom MOTD. Possible values are "true" or "false". Default value is false.

.B NOTE:
Be sure, that /etc/emptty/motd-gen.sh has correct content and permissions (e.g. 744), the script is started as default user; in daemon mode it means
.I root

.IP FG_COLOR
Foreground color, available only in daemon mode. List of colors is listed below.

.IP BG_COLOR
Background color, available only in daemon mode. List of colors is listed below.

.IP DISPLAY_START_SCRIPT
Script started before Display (Xorg/Wayland) starts.

.B NOTE:
The script is started as default user; in daemon mode it means
.I root

.IP DISPLAY_STOP_SCRIPT
Script started after Display (Xorg/Wayland) stops.

.B NOTE:
The script is started as default user; in daemon mode it means
.I root

.IP ENABLE_NUMLOCK
Enables numlock in daemon mode. Possible values are "true" or "false". Default value is false.

.IP SESSION_ERROR_LOGGING
Defines how logging of session errors is handled. Possible values are "default", "appending" or "disabled". Default value is "disabled".
.IP SESSION_ERROR_LOGGING_FILE
Overrides path of session errors log file. Default value is
.I /var/log/emptty-session-errors

.B NOTE:
It expects existence of directories to defined logging file.

.SH DYNAMIC MOTD
Optional file stored as /etc/emptty/motd-gen.sh

If
.IDYNAMIC_MOTD
is set to true, this file exists and is executable for its owner, the result is printed as your own MOTD. Be very careful with this script!

.SH CUSTOM MOTD
Optional file stored as /etc/emptty/motd

Custom file, that prints your own MOTD. Reading this file supports colors (e.g.
.I \\\x1b[31m
or
.I \\\033[32m
)

.SH USER CONFIG
Optional file stored as ${HOME}/.config/emptty or ${HOME}/.emptty

Configuration file stored as ${HOME}/.config/emptty has higher priority on loading.
.IP Name
Optional name to be used as Session Name.
.IP Exec
Defines command to start Desktop Environment/Window Manager. This value does not need to be defined, if .emptty file is presented as shell script (with shebang at the start and execution permissions).
.IP Environment
Selects, which environment should be defined for following command. Possible values are "xorg" and "wayland", "xorg" is default.
.IP Lang
Defines locale for logged user, has higher priority than LANG from global configuration
.IP Selection
Requires selection of desktop, basically turns
.I emptty
file into
.I .xinitrc
for Xorg and Wayland. In this case
.I Exec
is skipped.

.SH CUSTOM SESSIONS
Optional folders for custom sessions, that could be available system-wide (in case of /etc/emptty/custom-sessions/) or user-specific (in case of ${HOME}/.config/emptty-custom-sessions/), but do not have .desktop file stored on standard paths for Xorg or Wayland sessions. Expected suffix of each file is ".desktop".

.IP Name
Defines name of Desktop Environment/Window Manager.
.IP Exec
Defines command to start Desktop Environment/Window Manager.
.IP Environment
Selects, which environment should be defined for following command. Possible values are "xorg" and "wayland", "xorg" is default.

.SH LAST SESSION
The last user selection of session is stored into ~/.cache/emptty/last-session

.SH LOGGING
As it is mentioned in configuration, there are three options to handle logging of emptty. The logs contains not just logs from emptty, but also from Xorg (if used) and user's WM/DE.
Described log location could differ according configuration
.I LOGGING_FILE
, that is stored in
.I /etc/emptty/conf

.IP default
This option provides simple solution, when current instance of emptty logs into
.I /var/log/emptty
and the previous version is stored as
.I /var/log/emptty.old

.B NOTE:
Current instance always move previous log into old file, if emptty crashes and is started again, previous log is in
.I /var/log/emptty.old

.IP appending
This option provides functionality that logs everything into
.I /var/log/emptty
and does not handle log rotation by itself. It leaves the option for user to handle it himself (e.g. with logrotate).

.B NOTE:
Appending without roration could cause large log file, be sure that log file is rotated.

.IP disabled
This option points all log into
.I /dev/null
, so no log is available.

.B NOTE:
If any issue starts to appear and you want to report it, ensure you do not use this option.

.SH COLORS
Please, be aware that
.I LIGHT_
colors could be unavailable as background color.

BLACK, RED, GREEN, YELLOW, BLUE, PURPLE, CYAN, WHITE

LIGHT_BLACK, LIGHT_RED, LIGHT_GREEN, LIGHT_YELLOW, LIGHT_BLUE, LIGHT_PURPLE, LIGHT_CYAN, LIGHT_WHITE
