.TH EMPTTY 1 "July 2020" "emptty 0.2.2" emptty

.SH NAME
emptty \- Dead simple Display Manager running in CLI as TTY login.

.SH SYNOPSIS
.B emptty [-v] [--version] [-d] [--daemon]

.SH DESCRIPTION
.B emppty
Simple CLI Display Manager, that allows to select DE/WM after login, use predefined config or allows autologin, if selected user is part of
.I nopasswdlogin
group.

.SH OPTIONS
.IP "\-v, \-\-version"
Display the version of the program.

.IP "\-d, \-\-daemon"
Starts emptty as daemon, that does not require agetty.

.SH CONFIG
/etc/emptty/conf

.IP TTY_NUMBER
TTY, where emptty will start.
.IP SWITCH_TTY
Enables switching to defined TTY number. Default is true.
.IP PRINT_ISSUE
Enables printing of /etc/issue in daemon mode.
.IP DEFAULT_USER
Preselected user, if AUTOLOGIN is enabled, this user is logged in.
.IP AUTOLOGIN
Enables Autologin, if DEFAULT_USER is defined. Possible values are "true" or "false". Default value is false.

.B NOTE:
to enable autologin DEFAULT_USER must be in group
.I nopasswdlogin
, otherwise user will NOT be authorized.
.IP LANG
defines locale for all users. Default value is "en_US.UTF-8"
.IP DBUS_LAUNCH
Prepends "dbus-launch" before desktop command. Default value is true. If
.I .emptty
is handled as script, this config is overriden to false.
.IP XINITRC_LAUNCH
Starts Xorg desktop with calling
.I ~/.xinitrc
script, if is true, file exists and selected WM/DE is Xorg session, it overrides DBUS_LAUNCH. If
.I .emptty
is handled as script, this config is overriden to false.

.SH CUSTOM MOTD
Optional file stored as /etc/emptty/motd

Custom file, that prints your own MOTD. Reading this file supports colors (e.g.
.I \\\x1b[31m
or
.I \\\033[32m
)

.SH USER CONFIG
Optional file stored as ${HOME}/.emptty
.IP ENVIRONMENT
Selects, which environment should be defined for following command. Possible values are "xorg" and "wayland", "xorg" is default.
.IP COMMAND
Defines command to start Desktop Environment/Window Manager. This value does not need to be defined, if .emptty file is presented as shell script (with shebang at the start and execution permissions).
.IP LANG
Defines locale for logged user, has higher priority than LANG from global configuration

.SH CUSTOM SESSIONS
Optional folder for custom sessions, that could be available system-wide, but do not have .desktop file stored on standard paths for Xorg or Wayland sessions. Expected suffix of each file is ".desktop".

.IP Name
Defines name of Desktop Environment/Window Manager.
.IP Exec
Defines command to start Desktop Environment/Window Manager.
.IP Environment
Selects, which environment should be defined for following command. Possible values are "xorg" and "wayland", "xorg" is default.